/* Generated by re2c 4.3 on Fri May 22 22:48:55 2026 */
#line 1 "lexer.re"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lexer.h"
#include "parser.h"

#ifdef _WIN32
static char *js_strndup(const char *s, size_t n) {
    char *copy = (char *)malloc(n + 1);
    if (!copy) {
        return NULL;
    }
    memcpy(copy, s, n);
    copy[n] = '\0';
    return copy;
}
#else
#define js_strndup strndup
#endif

// 扫描器状态：re2c 通过 cursor/marker 推进输入；line/column 用于错误和 ASI 报告。
typedef struct {
    const char *start;
    const char *cursor;
    const char *marker;
    const char *ctxmarker;
    int line;
    int column;
    int last_token_line;
    int last_token_column;
    int last_token;
    int brace_stack[256];
    int brace_top;
    int last_closed_brace_was_object;
} Scanner;

static Scanner scanner;

// 初始化词法分析器状态。每次重新解析同一份输入时都要调用。
void init_scanner(const char *input) {
    scanner.start = input;
    scanner.cursor = input;
    scanner.marker = NULL;
    scanner.ctxmarker = NULL;
    scanner.line = 1;
    scanner.column = 1;
    scanner.last_token_line = 1;
    scanner.last_token_column = 1;
    scanner.last_token = 0;
    scanner.brace_top = 0;
    scanner.last_closed_brace_was_object = 0;
}

// 从输入开头重新计算当前位置。当前项目输入较小，这种写法简单可靠。
static void update_position() {
    const char *p = scanner.start;
    int line = 1;
    int column = 1;
    
    while (p < scanner.cursor) {
        if (*p == '\n') {
            line++;
            column = 1;
        } else {
            column++;
        }
        p++;
    }
    
    scanner.line = line;
    scanner.column = column;
    yylineno = line;
}

// 计算某个源码指针对应的 1-based 行号和列号。
static void pointer_position(const char *target, int *line, int *column) {
    const char *p = scanner.start;
    int current_line = 1;
    int current_column = 1;

    while (p < target) {
        if (*p == '\n') {
            current_line++;
            current_column = 1;
        } else {
            current_column++;
        }
        p++;
    }

    *line = current_line;
    *column = current_column;
}

// 打印 ASI 虚拟分号插入位置。AST 阶段复用 lexer 时会关闭该日志。
static void print_asi_insertion(const char *after_char) {
    int line;
    int column;

    if (!asi_report_enabled) {
        return;
    }
    pointer_position(after_char, &line, &column);
    printf("ASI: inserted virtual semicolon at line %d, column %d\n",
           line, column + 1);
}

// 返回当前行最后一个有效源码字符；行尾注释不参与 ASI 判断。
static const char *effective_line_end(const char *newline_start) {
    const char *line_start = newline_start;
    const char *p;

    while (line_start > scanner.start && line_start[-1] != '\n' && line_start[-1] != '\r') {
        line_start--;
    }

    for (p = line_start; p + 1 < newline_start; p++) {
        if (p[0] == '/' && p[1] == '/') {
            newline_start = p;
            break;
        }
    }

    p = newline_start;
    while (p > line_start) {
        --p;
        if (*p != ' ' && *p != '\t' && *p != '\v' && *p != '\f') {
            return p;
        }
    }

    return NULL;
}

// 返回 token 前维护少量上下文，用于区分对象字面量的 } 和普通代码块的 }。
static int token(int tok) {
    scanner.last_token_line = scanner.line;
    scanner.last_token_column = scanner.column;

    if (tok == LBRACE) {
        int is_object = 0;
        switch (scanner.last_token) {
            case ASSIGN:
            case PLUS_ASSIGN:
            case MINUS_ASSIGN:
            case MULTIPLY_ASSIGN:
            case DIVIDE_ASSIGN:
            case MODULO_ASSIGN:
            case EXPONENT_ASSIGN:
            case AND_ASSIGN:
            case OR_ASSIGN:
            case XOR_ASSIGN:
            case LEFT_SHIFT_ASSIGN:
            case RIGHT_SHIFT_ASSIGN:
            case UNSIGNED_RIGHT_SHIFT_ASSIGN:
            case LPAREN:
            case LBRACKET:
            case COMMA:
            case COLON:
            case QUESTION:
            case RETURN:
            case THROW:
            case ARROW:
                is_object = 1;
                break;
        }

        if (scanner.brace_top < (int)(sizeof(scanner.brace_stack) / sizeof(scanner.brace_stack[0]))) {
            scanner.brace_stack[scanner.brace_top++] = is_object;
        }
        scanner.last_closed_brace_was_object = 0;
    } else if (tok == RBRACE) {
        scanner.last_closed_brace_was_object = 0;
        if (scanner.brace_top > 0) {
            scanner.last_closed_brace_was_object = scanner.brace_stack[--scanner.brace_top];
        }
    } else if (tok != SEMICOLON) {
        scanner.last_closed_brace_was_object = 0;
    }

    scanner.last_token = tok;
    return tok;
}

#line 202 "lexer.re"


int yylex(void) {
    const char *start;
    
scan:
    start = scanner.cursor;
    update_position();
    

#line 199 "lexer.c"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	yych = *scanner.cursor;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\v':
		case '\f':
		case ' ': goto yy4;
		case '\n': goto yy6;
		case '\r': goto yy8;
		case '!': goto yy9;
		case '"': goto yy11;
		case '%': goto yy12;
		case '&': goto yy14;
		case '\'': goto yy16;
		case '(': goto yy17;
		case ')': goto yy18;
		case '*': goto yy19;
		case '+': goto yy21;
		case ',': goto yy23;
		case '-': goto yy24;
		case '.': goto yy26;
		case '/': goto yy28;
		case '0': goto yy30;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy32;
		case ':': goto yy34;
		case ';': goto yy35;
		case '<': goto yy36;
		case '=': goto yy38;
		case '>': goto yy40;
		case '?': goto yy42;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'm':
		case 'o':
		case 'p':
		case 'q':
		case 'u':
		case 'x':
		case 'z': goto yy44;
		case '[': goto yy47;
		case ']': goto yy48;
		case '^': goto yy49;
		case 'a': goto yy51;
		case 'b': goto yy52;
		case 'c': goto yy53;
		case 'd': goto yy54;
		case 'e': goto yy55;
		case 'f': goto yy56;
		case 'i': goto yy57;
		case 'l': goto yy58;
		case 'n': goto yy59;
		case 'r': goto yy60;
		case 's': goto yy61;
		case 't': goto yy62;
		case 'v': goto yy63;
		case 'w': goto yy64;
		case 'y': goto yy65;
		case '{': goto yy66;
		case '|': goto yy67;
		case '}': goto yy69;
		case '~': goto yy70;
		default: goto yy2;
	}
yy1:
	++scanner.cursor;
#line 389 "lexer.re"
	{ return 0; }
#line 307 "lexer.c"
yy2:
	++scanner.cursor;
yy3:
#line 392 "lexer.re"
	{ return token(ERROR_TOKEN); }
#line 313 "lexer.c"
yy4:
	yych = *++scanner.cursor;
	switch (yych) {
		case '\t':
		case '\v':
		case '\f':
		case ' ': goto yy4;
		default: goto yy5;
	}
yy5:
#line 213 "lexer.re"
	{ goto scan; }
#line 326 "lexer.c"
yy6:
	++scanner.cursor;
yy7:
#line 229 "lexer.re"
	{
        const char *p = effective_line_end(start);
        if (p == NULL) {
            goto scan;
        }
        if (strchr("{[(,.:;?*/%<>=!&|^~", *p) != NULL) {
            goto scan;
        }
        if ((*p == '+' || *p == '-') && (p == scanner.start || p[-1] != *p)) {
            goto scan;
        }
        if (*p == '}' && !scanner.last_closed_brace_was_object) {
            goto scan;
        }
        const char *q = scanner.cursor;
        while (*q == ' ' || *q == '\t' || *q == '\v' || *q == '\f') {
            ++q;
        }
        if (*q == ']' || *q == ')') {
            goto scan;
        }
        if (*q == '}' && scanner.brace_top > 0 && scanner.brace_stack[scanner.brace_top - 1]) {
            goto scan;
        }
        print_asi_insertion(p);
        return token(SEMICOLON);
    }
#line 358 "lexer.c"
yy8:
	yych = *++scanner.cursor;
	switch (yych) {
		case '\n': goto yy6;
		default: goto yy7;
	}
yy9:
	yych = *++scanner.cursor;
	switch (yych) {
		case '=': goto yy71;
		default: goto yy10;
	}
yy10:
#line 383 "lexer.re"
	{ return token(NOT); }
#line 374 "lexer.c"
yy11:
	yyaccept = 0;
	yych = *(scanner.marker = ++scanner.cursor);
	switch (yych) {
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\v':
		case '\f':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F:
		case 0xC2:
		case 0xC3:
		case 0xC4:
		case 0xC5:
		case 0xC6:
		case 0xC7:
		case 0xC8:
		case 0xC9:
		case 0xCA:
		case 0xCB:
		case 0xCC:
		case 0xCD:
		case 0xCE:
		case 0xCF:
		case 0xD0:
		case 0xD1:
		case 0xD2:
		case 0xD3:
		case 0xD4:
		case 0xD5:
		case 0xD6:
		case 0xD7:
		case 0xD8:
		case 0xD9:
		case 0xDA:
		case 0xDB:
		case 0xDC:
		case 0xDD:
		case 0xDE:
		case 0xDF:
		case 0xE0:
		case 0xE1:
		case 0xE2:
		case 0xE3:
		case 0xE4:
		case 0xE5:
		case 0xE6:
		case 0xE7:
		case 0xE8:
		case 0xE9:
		case 0xEA:
		case 0xEB:
		case 0xEC:
		case 0xED:
		case 0xEE:
		case 0xEF:
		case 0xF0:
		case 0xF1:
		case 0xF2:
		case 0xF3:
		case 0xF4: goto yy74;
		default: goto yy3;
	}
yy12:
	yych = *++scanner.cursor;
	switch (yych) {
		case '=': goto yy84;
		default: goto yy13;
	}
yy13:
#line 379 "lexer.re"
	{ return token(MODULO); }
#line 566 "lexer.c"
yy14:
	yych = *++scanner.cursor;
	switch (yych) {
		case '&': goto yy85;
		case '=': goto yy86;
		default: goto yy15;
	}
yy15:
#line 384 "lexer.re"
	{ return token(BITWISE_AND); }
#line 577 "lexer.c"
yy16:
	yyaccept = 0;
	yych = *(scanner.marker = ++scanner.cursor);
	switch (yych) {
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\v':
		case '\f':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F:
		case 0xC2:
		case 0xC3:
		case 0xC4:
		case 0xC5:
		case 0xC6:
		case 0xC7:
		case 0xC8:
		case 0xC9:
		case 0xCA:
		case 0xCB:
		case 0xCC:
		case 0xCD:
		case 0xCE:
		case 0xCF:
		case 0xD0:
		case 0xD1:
		case 0xD2:
		case 0xD3:
		case 0xD4:
		case 0xD5:
		case 0xD6:
		case 0xD7:
		case 0xD8:
		case 0xD9:
		case 0xDA:
		case 0xDB:
		case 0xDC:
		case 0xDD:
		case 0xDE:
		case 0xDF:
		case 0xE0:
		case 0xE1:
		case 0xE2:
		case 0xE3:
		case 0xE4:
		case 0xE5:
		case 0xE6:
		case 0xE7:
		case 0xE8:
		case 0xE9:
		case 0xEA:
		case 0xEB:
		case 0xEC:
		case 0xED:
		case 0xEE:
		case 0xEF:
		case 0xF0:
		case 0xF1:
		case 0xF2:
		case 0xF3:
		case 0xF4: goto yy88;
		default: goto yy3;
	}
yy17:
	++scanner.cursor;
#line 371 "lexer.re"
	{ return token(LPAREN); }
#line 764 "lexer.c"
yy18:
	++scanner.cursor;
#line 372 "lexer.re"
	{ return token(RPAREN); }
#line 769 "lexer.c"
yy19:
	yych = *++scanner.cursor;
	switch (yych) {
		case '*': goto yy97;
		case '=': goto yy99;
		default: goto yy20;
	}
yy20:
#line 377 "lexer.re"
	{ return token(MULTIPLY); }
#line 780 "lexer.c"
yy21:
	yych = *++scanner.cursor;
	switch (yych) {
		case '+': goto yy100;
		case '=': goto yy101;
		default: goto yy22;
	}
yy22:
#line 375 "lexer.re"
	{ return token(PLUS); }
#line 791 "lexer.c"
yy23:
	++scanner.cursor;
#line 364 "lexer.re"
	{ return token(COMMA); }
#line 796 "lexer.c"
yy24:
	yych = *++scanner.cursor;
	switch (yych) {
		case '-': goto yy102;
		case '=': goto yy103;
		default: goto yy25;
	}
yy25:
#line 376 "lexer.re"
	{ return token(MINUS); }
#line 807 "lexer.c"
yy26:
	yyaccept = 1;
	yych = *(scanner.marker = ++scanner.cursor);
	switch (yych) {
		case '.': goto yy104;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy105;
		default: goto yy27;
	}
yy27:
#line 366 "lexer.re"
	{ return token(DOT); }
#line 828 "lexer.c"
yy28:
	yych = *++scanner.cursor;
	switch (yych) {
		case '*': goto yy107;
		case '/': goto yy108;
		case '=': goto yy110;
		default: goto yy29;
	}
yy29:
#line 378 "lexer.re"
	{ return token(DIVIDE); }
#line 840 "lexer.c"
yy30:
	yyaccept = 2;
	yych = *(scanner.marker = ++scanner.cursor);
	switch (yych) {
		case 'x': goto yy112;
		default: goto yy33;
	}
yy31:
#line 263 "lexer.re"
	{
        yylval.number = strtod(start, NULL);
        return token(NUMBER);
    }
#line 854 "lexer.c"
yy32:
	yyaccept = 2;
	yych = *(scanner.marker = ++scanner.cursor);
yy33:
	switch (yych) {
		case '.': goto yy105;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy32;
		case 'E':
		case 'e': goto yy111;
		default: goto yy31;
	}
yy34:
	++scanner.cursor;
#line 365 "lexer.re"
	{ return token(COLON); }
#line 879 "lexer.c"
yy35:
	++scanner.cursor;
#line 363 "lexer.re"
	{ return token(SEMICOLON); }
#line 884 "lexer.c"
yy36:
	yych = *++scanner.cursor;
	switch (yych) {
		case '<': goto yy113;
		case '=': goto yy115;
		default: goto yy37;
	}
yy37:
#line 380 "lexer.re"
	{ return token(LESS); }
#line 895 "lexer.c"
yy38:
	yych = *++scanner.cursor;
	switch (yych) {
		case '=': goto yy116;
		case '>': goto yy118;
		default: goto yy39;
	}
yy39:
#line 382 "lexer.re"
	{ return token(ASSIGN); }
#line 906 "lexer.c"
yy40:
	yych = *++scanner.cursor;
	switch (yych) {
		case '=': goto yy119;
		case '>': goto yy120;
		default: goto yy41;
	}
yy41:
#line 381 "lexer.re"
	{ return token(GREATER); }
#line 917 "lexer.c"
yy42:
	yych = *++scanner.cursor;
	switch (yych) {
		case '.': goto yy122;
		case '?': goto yy123;
		default: goto yy43;
	}
yy43:
#line 373 "lexer.re"
	{ return token(QUESTION); }
#line 928 "lexer.c"
yy44:
	yych = *++scanner.cursor;
yy45:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy46;
	}
yy46:
#line 325 "lexer.re"
	{
        yylval.string = js_strndup(start, scanner.cursor - start);
        return token(IDENTIFIER);
    }
#line 1004 "lexer.c"
yy47:
	++scanner.cursor;
#line 369 "lexer.re"
	{ return token(LBRACKET); }
#line 1009 "lexer.c"
yy48:
	++scanner.cursor;
#line 370 "lexer.re"
	{ return token(RBRACKET); }
#line 1014 "lexer.c"
yy49:
	yych = *++scanner.cursor;
	switch (yych) {
		case '=': goto yy124;
		default: goto yy50;
	}
yy50:
#line 386 "lexer.re"
	{ return token(BITWISE_XOR); }
#line 1024 "lexer.c"
yy51:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'w': goto yy125;
		default: goto yy45;
	}
yy52:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'r': goto yy126;
		default: goto yy45;
	}
yy53:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'a': goto yy127;
		case 'l': goto yy128;
		case 'o': goto yy129;
		default: goto yy45;
	}
yy54:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy130;
		case 'o': goto yy131;
		default: goto yy45;
	}
yy55:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'l': goto yy133;
		case 'x': goto yy134;
		default: goto yy45;
	}
yy56:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'a': goto yy135;
		case 'i': goto yy136;
		case 'o': goto yy137;
		case 'u': goto yy138;
		default: goto yy45;
	}
yy57:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'f': goto yy139;
		case 'm': goto yy141;
		case 'n': goto yy142;
		default: goto yy45;
	}
yy58:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy144;
		default: goto yy45;
	}
yy59:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy145;
		case 'u': goto yy146;
		default: goto yy45;
	}
yy60:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy147;
		default: goto yy45;
	}
yy61:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'u': goto yy148;
		case 'w': goto yy149;
		default: goto yy45;
	}
yy62:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'h': goto yy150;
		case 'r': goto yy151;
		case 'y': goto yy152;
		default: goto yy45;
	}
yy63:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'a': goto yy153;
		case 'o': goto yy154;
		default: goto yy45;
	}
yy64:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'h': goto yy155;
		case 'i': goto yy156;
		default: goto yy45;
	}
yy65:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'i': goto yy157;
		default: goto yy45;
	}
yy66:
	++scanner.cursor;
#line 367 "lexer.re"
	{ return token(LBRACE); }
#line 1134 "lexer.c"
yy67:
	yych = *++scanner.cursor;
	switch (yych) {
		case '=': goto yy158;
		case '|': goto yy159;
		default: goto yy68;
	}
yy68:
#line 385 "lexer.re"
	{ return token(BITWISE_OR); }
#line 1145 "lexer.c"
yy69:
	++scanner.cursor;
#line 368 "lexer.re"
	{ return token(RBRACE); }
#line 1150 "lexer.c"
yy70:
	++scanner.cursor;
#line 374 "lexer.re"
	{ return token(BITWISE_NOT); }
#line 1155 "lexer.c"
yy71:
	yych = *++scanner.cursor;
	switch (yych) {
		case '=': goto yy160;
		default: goto yy72;
	}
yy72:
#line 334 "lexer.re"
	{ return token(NOT_EQUAL); }
#line 1165 "lexer.c"
yy73:
	yych = *++scanner.cursor;
yy74:
	switch (yych) {
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\v':
		case '\f':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy73;
		case '"': goto yy76;
		case '\\': goto yy77;
		case 0xC2:
		case 0xC3:
		case 0xC4:
		case 0xC5:
		case 0xC6:
		case 0xC7:
		case 0xC8:
		case 0xC9:
		case 0xCA:
		case 0xCB:
		case 0xCC:
		case 0xCD:
		case 0xCE:
		case 0xCF:
		case 0xD0:
		case 0xD1:
		case 0xD2:
		case 0xD3:
		case 0xD4:
		case 0xD5:
		case 0xD6:
		case 0xD7:
		case 0xD8:
		case 0xD9:
		case 0xDA:
		case 0xDB:
		case 0xDC:
		case 0xDD:
		case 0xDE:
		case 0xDF: goto yy78;
		case 0xE0: goto yy79;
		case 0xE1:
		case 0xE2:
		case 0xE3:
		case 0xE4:
		case 0xE5:
		case 0xE6:
		case 0xE7:
		case 0xE8:
		case 0xE9:
		case 0xEA:
		case 0xEB:
		case 0xEC:
		case 0xED:
		case 0xEE:
		case 0xEF: goto yy80;
		case 0xF0: goto yy81;
		case 0xF1:
		case 0xF2:
		case 0xF3: goto yy82;
		case 0xF4: goto yy83;
		default: goto yy75;
	}
yy75:
	scanner.cursor = scanner.marker;
	switch (yyaccept) {
		case 0: goto yy3;
		case 1: goto yy27;
		case 2: goto yy31;
		case 3: goto yy106;
		default: goto yy109;
	}
yy76:
	++scanner.cursor;
#line 274 "lexer.re"
	{
        yylval.string = js_strndup(start + 1, (scanner.cursor - start) - 2);
        return token(STRING);
    }
#line 1364 "lexer.c"
yy77:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy73;
		case 0xC2:
		case 0xC3: goto yy78;
		default: goto yy75;
	}
yy78:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy73;
		default: goto yy75;
	}
yy79:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy78;
		default: goto yy75;
	}
yy80:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy78;
		default: goto yy75;
	}
yy81:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy80;
		default: goto yy75;
	}
yy82:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy80;
		default: goto yy75;
	}
yy83:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F: goto yy80;
		default: goto yy75;
	}
yy84:
	++scanner.cursor;
#line 348 "lexer.re"
	{ return token(MODULO_ASSIGN); }
#line 1821 "lexer.c"
yy85:
	++scanner.cursor;
#line 337 "lexer.re"
	{ return token(LOGICAL_AND); }
#line 1826 "lexer.c"
yy86:
	++scanner.cursor;
#line 349 "lexer.re"
	{ return token(AND_ASSIGN); }
#line 1831 "lexer.c"
yy87:
	yych = *++scanner.cursor;
yy88:
	switch (yych) {
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\v':
		case '\f':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy87;
		case '\'': goto yy89;
		case '\\': goto yy90;
		case 0xC2:
		case 0xC3:
		case 0xC4:
		case 0xC5:
		case 0xC6:
		case 0xC7:
		case 0xC8:
		case 0xC9:
		case 0xCA:
		case 0xCB:
		case 0xCC:
		case 0xCD:
		case 0xCE:
		case 0xCF:
		case 0xD0:
		case 0xD1:
		case 0xD2:
		case 0xD3:
		case 0xD4:
		case 0xD5:
		case 0xD6:
		case 0xD7:
		case 0xD8:
		case 0xD9:
		case 0xDA:
		case 0xDB:
		case 0xDC:
		case 0xDD:
		case 0xDE:
		case 0xDF: goto yy91;
		case 0xE0: goto yy92;
		case 0xE1:
		case 0xE2:
		case 0xE3:
		case 0xE4:
		case 0xE5:
		case 0xE6:
		case 0xE7:
		case 0xE8:
		case 0xE9:
		case 0xEA:
		case 0xEB:
		case 0xEC:
		case 0xED:
		case 0xEE:
		case 0xEF: goto yy93;
		case 0xF0: goto yy94;
		case 0xF1:
		case 0xF2:
		case 0xF3: goto yy95;
		case 0xF4: goto yy96;
		default: goto yy75;
	}
yy89:
	++scanner.cursor;
#line 279 "lexer.re"
	{
        yylval.string = js_strndup(start + 1, (scanner.cursor - start) - 2);
        return token(STRING);
    }
#line 2021 "lexer.c"
yy90:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy87;
		case 0xC2:
		case 0xC3: goto yy91;
		default: goto yy75;
	}
yy91:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy87;
		default: goto yy75;
	}
yy92:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy91;
		default: goto yy75;
	}
yy93:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy91;
		default: goto yy75;
	}
yy94:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy93;
		default: goto yy75;
	}
yy95:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy93;
		default: goto yy75;
	}
yy96:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F: goto yy93;
		default: goto yy75;
	}
yy97:
	yych = *++scanner.cursor;
	switch (yych) {
		case '=': goto yy161;
		default: goto yy98;
	}
yy98:
#line 357 "lexer.re"
	{ return token(EXPONENT); }
#line 2483 "lexer.c"
yy99:
	++scanner.cursor;
#line 346 "lexer.re"
	{ return token(MULTIPLY_ASSIGN); }
#line 2488 "lexer.c"
yy100:
	++scanner.cursor;
#line 339 "lexer.re"
	{ return token(INCREMENT); }
#line 2493 "lexer.c"
yy101:
	++scanner.cursor;
#line 344 "lexer.re"
	{ return token(PLUS_ASSIGN); }
#line 2498 "lexer.c"
yy102:
	++scanner.cursor;
#line 340 "lexer.re"
	{ return token(DECREMENT); }
#line 2503 "lexer.c"
yy103:
	++scanner.cursor;
#line 345 "lexer.re"
	{ return token(MINUS_ASSIGN); }
#line 2508 "lexer.c"
yy104:
	yych = *++scanner.cursor;
	switch (yych) {
		case '.': goto yy162;
		default: goto yy75;
	}
yy105:
	yyaccept = 3;
	yych = *(scanner.marker = ++scanner.cursor);
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy105;
		case 'E':
		case 'e': goto yy111;
		default: goto yy106;
	}
yy106:
#line 258 "lexer.re"
	{
        yylval.number = strtod(start, NULL);
        return token(NUMBER);
    }
#line 2539 "lexer.c"
yy107:
	++scanner.cursor;
#line 215 "lexer.re"
	{
        while (*scanner.cursor != '\0') {
            if (scanner.cursor[0] == '*' && scanner.cursor[1] == '/') {
                scanner.cursor += 2;
                goto scan;
            }
            scanner.cursor++;
        }
        return token(ERROR_TOKEN);
    }
#line 2553 "lexer.c"
yy108:
	yyaccept = 4;
	yych = *(scanner.marker = ++scanner.cursor);
	switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case '\t':
		case '\v':
		case '\f':
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case ' ':
		case '!':
		case '"':
		case '#':
		case '$':
		case '%':
		case '&':
		case '\'':
		case '(':
		case ')':
		case '*':
		case '+':
		case ',':
		case '-':
		case '.':
		case '/':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case ':':
		case ';':
		case '<':
		case '=':
		case '>':
		case '?':
		case '@':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '_':
		case '`':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F: goto yy108;
		case 0xC2:
		case 0xC3:
		case 0xC4:
		case 0xC5:
		case 0xC6:
		case 0xC7:
		case 0xC8:
		case 0xC9:
		case 0xCA:
		case 0xCB:
		case 0xCC:
		case 0xCD:
		case 0xCE:
		case 0xCF:
		case 0xD0:
		case 0xD1:
		case 0xD2:
		case 0xD3:
		case 0xD4:
		case 0xD5:
		case 0xD6:
		case 0xD7:
		case 0xD8:
		case 0xD9:
		case 0xDA:
		case 0xDB:
		case 0xDC:
		case 0xDD:
		case 0xDE:
		case 0xDF: goto yy163;
		case 0xE0: goto yy164;
		case 0xE1:
		case 0xE2:
		case 0xE3:
		case 0xE4:
		case 0xE5:
		case 0xE6:
		case 0xE7:
		case 0xE8:
		case 0xE9:
		case 0xEA:
		case 0xEB:
		case 0xEC:
		case 0xED:
		case 0xEE:
		case 0xEF: goto yy165;
		case 0xF0: goto yy166;
		case 0xF1:
		case 0xF2:
		case 0xF3: goto yy167;
		case 0xF4: goto yy168;
		default: goto yy109;
	}
yy109:
#line 226 "lexer.re"
	{ goto scan; }
#line 2740 "lexer.c"
yy110:
	++scanner.cursor;
#line 347 "lexer.re"
	{ return token(DIVIDE_ASSIGN); }
#line 2745 "lexer.c"
yy111:
	yych = *++scanner.cursor;
	switch (yych) {
		case '+':
		case '-': goto yy169;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy170;
		default: goto yy75;
	}
yy112:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy171;
		default: goto yy75;
	}
yy113:
	yych = *++scanner.cursor;
	switch (yych) {
		case '=': goto yy173;
		default: goto yy114;
	}
yy114:
#line 341 "lexer.re"
	{ return token(LEFT_SHIFT); }
#line 2799 "lexer.c"
yy115:
	++scanner.cursor;
#line 335 "lexer.re"
	{ return token(LESS_EQUAL); }
#line 2804 "lexer.c"
yy116:
	yych = *++scanner.cursor;
	switch (yych) {
		case '=': goto yy174;
		default: goto yy117;
	}
yy117:
#line 333 "lexer.re"
	{ return token(EQUAL); }
#line 2814 "lexer.c"
yy118:
	++scanner.cursor;
#line 360 "lexer.re"
	{ return token(ARROW); }
#line 2819 "lexer.c"
yy119:
	++scanner.cursor;
#line 336 "lexer.re"
	{ return token(GREATER_EQUAL); }
#line 2824 "lexer.c"
yy120:
	yych = *++scanner.cursor;
	switch (yych) {
		case '=': goto yy175;
		case '>': goto yy176;
		default: goto yy121;
	}
yy121:
#line 342 "lexer.re"
	{ return token(RIGHT_SHIFT); }
#line 2835 "lexer.c"
yy122:
	++scanner.cursor;
#line 359 "lexer.re"
	{ return token(OPTIONAL_CHAINING); }
#line 2840 "lexer.c"
yy123:
	++scanner.cursor;
#line 358 "lexer.re"
	{ return token(NULLISH_COALESCING); }
#line 2845 "lexer.c"
yy124:
	++scanner.cursor;
#line 351 "lexer.re"
	{ return token(XOR_ASSIGN); }
#line 2850 "lexer.c"
yy125:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'a': goto yy178;
		default: goto yy45;
	}
yy126:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy179;
		default: goto yy45;
	}
yy127:
	yych = *++scanner.cursor;
	switch (yych) {
		case 's': goto yy180;
		case 't': goto yy181;
		default: goto yy45;
	}
yy128:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'a': goto yy182;
		default: goto yy45;
	}
yy129:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'n': goto yy183;
		default: goto yy45;
	}
yy130:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'b': goto yy184;
		case 'f': goto yy185;
		case 'l': goto yy186;
		default: goto yy45;
	}
yy131:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy132;
	}
yy132:
#line 294 "lexer.re"
	{ return token(DO); }
#line 2961 "lexer.c"
yy133:
	yych = *++scanner.cursor;
	switch (yych) {
		case 's': goto yy187;
		default: goto yy45;
	}
yy134:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'p': goto yy188;
		case 't': goto yy189;
		default: goto yy45;
	}
yy135:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'l': goto yy190;
		default: goto yy45;
	}
yy136:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'n': goto yy191;
		default: goto yy45;
	}
yy137:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'r': goto yy192;
		default: goto yy45;
	}
yy138:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'n': goto yy194;
		default: goto yy45;
	}
yy139:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy140;
	}
yy140:
#line 301 "lexer.re"
	{ return token(IF); }
#line 3070 "lexer.c"
yy141:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'p': goto yy195;
		default: goto yy45;
	}
yy142:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		case 's': goto yy196;
		default: goto yy143;
	}
yy143:
#line 303 "lexer.re"
	{ return token(IN); }
#line 3148 "lexer.c"
yy144:
	yych = *++scanner.cursor;
	switch (yych) {
		case 't': goto yy197;
		default: goto yy45;
	}
yy145:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'w': goto yy199;
		default: goto yy45;
	}
yy146:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'l': goto yy201;
		default: goto yy45;
	}
yy147:
	yych = *++scanner.cursor;
	switch (yych) {
		case 't': goto yy202;
		default: goto yy45;
	}
yy148:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'p': goto yy203;
		default: goto yy45;
	}
yy149:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'i': goto yy204;
		default: goto yy45;
	}
yy150:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'i': goto yy205;
		case 'r': goto yy206;
		default: goto yy45;
	}
yy151:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'u': goto yy207;
		case 'y': goto yy208;
		default: goto yy45;
	}
yy152:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'p': goto yy210;
		default: goto yy45;
	}
yy153:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'r': goto yy211;
		default: goto yy45;
	}
yy154:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'i': goto yy213;
		default: goto yy45;
	}
yy155:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'i': goto yy214;
		default: goto yy45;
	}
yy156:
	yych = *++scanner.cursor;
	switch (yych) {
		case 't': goto yy215;
		default: goto yy45;
	}
yy157:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy216;
		default: goto yy45;
	}
yy158:
	++scanner.cursor;
#line 350 "lexer.re"
	{ return token(OR_ASSIGN); }
#line 3239 "lexer.c"
yy159:
	++scanner.cursor;
#line 338 "lexer.re"
	{ return token(LOGICAL_OR); }
#line 3244 "lexer.c"
yy160:
	++scanner.cursor;
#line 332 "lexer.re"
	{ return token(STRICT_NOT_EQUAL); }
#line 3249 "lexer.c"
yy161:
	++scanner.cursor;
#line 356 "lexer.re"
	{ return token(EXPONENT_ASSIGN); }
#line 3254 "lexer.c"
yy162:
	++scanner.cursor;
#line 355 "lexer.re"
	{ return token(SPREAD); }
#line 3259 "lexer.c"
yy163:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy108;
		default: goto yy75;
	}
yy164:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy163;
		default: goto yy75;
	}
yy165:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy163;
		default: goto yy75;
	}
yy166:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy165;
		default: goto yy75;
	}
yy167:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F:
		case 0x90:
		case 0x91:
		case 0x92:
		case 0x93:
		case 0x94:
		case 0x95:
		case 0x96:
		case 0x97:
		case 0x98:
		case 0x99:
		case 0x9A:
		case 0x9B:
		case 0x9C:
		case 0x9D:
		case 0x9E:
		case 0x9F:
		case 0xA0:
		case 0xA1:
		case 0xA2:
		case 0xA3:
		case 0xA4:
		case 0xA5:
		case 0xA6:
		case 0xA7:
		case 0xA8:
		case 0xA9:
		case 0xAA:
		case 0xAB:
		case 0xAC:
		case 0xAD:
		case 0xAE:
		case 0xAF:
		case 0xB0:
		case 0xB1:
		case 0xB2:
		case 0xB3:
		case 0xB4:
		case 0xB5:
		case 0xB6:
		case 0xB7:
		case 0xB8:
		case 0xB9:
		case 0xBA:
		case 0xBB:
		case 0xBC:
		case 0xBD:
		case 0xBE:
		case 0xBF: goto yy165;
		default: goto yy75;
	}
yy168:
	yych = *++scanner.cursor;
	switch (yych) {
		case 0x80:
		case 0x81:
		case 0x82:
		case 0x83:
		case 0x84:
		case 0x85:
		case 0x86:
		case 0x87:
		case 0x88:
		case 0x89:
		case 0x8A:
		case 0x8B:
		case 0x8C:
		case 0x8D:
		case 0x8E:
		case 0x8F: goto yy165;
		default: goto yy75;
	}
yy169:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy170;
		default: goto yy75;
	}
yy170:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy170;
		default: goto yy106;
	}
yy171:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy171;
		default: goto yy172;
	}
yy172:
#line 268 "lexer.re"
	{
        yylval.number = strtol(start, NULL, 16);
        return token(NUMBER);
    }
#line 3641 "lexer.c"
yy173:
	++scanner.cursor;
#line 352 "lexer.re"
	{ return token(LEFT_SHIFT_ASSIGN); }
#line 3646 "lexer.c"
yy174:
	++scanner.cursor;
#line 331 "lexer.re"
	{ return token(STRICT_EQUAL); }
#line 3651 "lexer.c"
yy175:
	++scanner.cursor;
#line 353 "lexer.re"
	{ return token(RIGHT_SHIFT_ASSIGN); }
#line 3656 "lexer.c"
yy176:
	yych = *++scanner.cursor;
	switch (yych) {
		case '=': goto yy217;
		default: goto yy177;
	}
yy177:
#line 343 "lexer.re"
	{ return token(UNSIGNED_RIGHT_SHIFT); }
#line 3666 "lexer.c"
yy178:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'i': goto yy218;
		default: goto yy45;
	}
yy179:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'a': goto yy219;
		default: goto yy45;
	}
yy180:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy220;
		default: goto yy45;
	}
yy181:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'c': goto yy222;
		default: goto yy45;
	}
yy182:
	yych = *++scanner.cursor;
	switch (yych) {
		case 's': goto yy223;
		default: goto yy45;
	}
yy183:
	yych = *++scanner.cursor;
	switch (yych) {
		case 's': goto yy224;
		case 't': goto yy225;
		default: goto yy45;
	}
yy184:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'u': goto yy226;
		default: goto yy45;
	}
yy185:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'a': goto yy227;
		default: goto yy45;
	}
yy186:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy228;
		default: goto yy45;
	}
yy187:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy229;
		default: goto yy45;
	}
yy188:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'o': goto yy231;
		default: goto yy45;
	}
yy189:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy232;
		default: goto yy45;
	}
yy190:
	yych = *++scanner.cursor;
	switch (yych) {
		case 's': goto yy233;
		default: goto yy45;
	}
yy191:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'a': goto yy234;
		default: goto yy45;
	}
yy192:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy193;
	}
yy193:
#line 299 "lexer.re"
	{ return token(FOR); }
#line 3823 "lexer.c"
yy194:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'c': goto yy235;
		default: goto yy45;
	}
yy195:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'o': goto yy236;
		default: goto yy45;
	}
yy196:
	yych = *++scanner.cursor;
	switch (yych) {
		case 't': goto yy237;
		default: goto yy45;
	}
yy197:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy198;
	}
yy198:
#line 305 "lexer.re"
	{ return token(LET); }
#line 3913 "lexer.c"
yy199:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy200;
	}
yy200:
#line 306 "lexer.re"
	{ return token(NEW); }
#line 3985 "lexer.c"
yy201:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'l': goto yy238;
		default: goto yy45;
	}
yy202:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'u': goto yy240;
		default: goto yy45;
	}
yy203:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy241;
		default: goto yy45;
	}
yy204:
	yych = *++scanner.cursor;
	switch (yych) {
		case 't': goto yy242;
		default: goto yy45;
	}
yy205:
	yych = *++scanner.cursor;
	switch (yych) {
		case 's': goto yy243;
		default: goto yy45;
	}
yy206:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'o': goto yy245;
		default: goto yy45;
	}
yy207:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy246;
		default: goto yy45;
	}
yy208:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy209;
	}
yy209:
#line 312 "lexer.re"
	{ return token(TRY); }
#line 4099 "lexer.c"
yy210:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy248;
		default: goto yy45;
	}
yy211:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy212;
	}
yy212:
#line 314 "lexer.re"
	{ return token(VAR); }
#line 4177 "lexer.c"
yy213:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'd': goto yy249;
		default: goto yy45;
	}
yy214:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'l': goto yy251;
		default: goto yy45;
	}
yy215:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'h': goto yy252;
		default: goto yy45;
	}
yy216:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'l': goto yy254;
		default: goto yy45;
	}
yy217:
	++scanner.cursor;
#line 354 "lexer.re"
	{ return token(UNSIGNED_RIGHT_SHIFT_ASSIGN); }
#line 4206 "lexer.c"
yy218:
	yych = *++scanner.cursor;
	switch (yych) {
		case 't': goto yy255;
		default: goto yy45;
	}
yy219:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'k': goto yy257;
		default: goto yy45;
	}
yy220:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy221;
	}
yy221:
#line 286 "lexer.re"
	{ return token(CASE); }
#line 4290 "lexer.c"
yy222:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'h': goto yy259;
		default: goto yy45;
	}
yy223:
	yych = *++scanner.cursor;
	switch (yych) {
		case 's': goto yy261;
		default: goto yy45;
	}
yy224:
	yych = *++scanner.cursor;
	switch (yych) {
		case 't': goto yy263;
		default: goto yy45;
	}
yy225:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'i': goto yy265;
		default: goto yy45;
	}
yy226:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'g': goto yy266;
		default: goto yy45;
	}
yy227:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'u': goto yy267;
		default: goto yy45;
	}
yy228:
	yych = *++scanner.cursor;
	switch (yych) {
		case 't': goto yy268;
		default: goto yy45;
	}
yy229:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy230;
	}
yy230:
#line 295 "lexer.re"
	{ return token(ELSE); }
#line 4404 "lexer.c"
yy231:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'r': goto yy269;
		default: goto yy45;
	}
yy232:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'n': goto yy270;
		default: goto yy45;
	}
yy233:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy271;
		default: goto yy45;
	}
yy234:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'l': goto yy273;
		default: goto yy45;
	}
yy235:
	yych = *++scanner.cursor;
	switch (yych) {
		case 't': goto yy274;
		default: goto yy45;
	}
yy236:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'r': goto yy275;
		default: goto yy45;
	}
yy237:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'a': goto yy276;
		default: goto yy45;
	}
yy238:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy239;
	}
yy239:
#line 320 "lexer.re"
	{ yylval.string = js_strndup("null", 4); return token(NULL_LITERAL); }
#line 4518 "lexer.c"
yy240:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'r': goto yy277;
		default: goto yy45;
	}
yy241:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'r': goto yy278;
		default: goto yy45;
	}
yy242:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'c': goto yy280;
		default: goto yy45;
	}
yy243:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy244;
	}
yy244:
#line 310 "lexer.re"
	{ return token(THIS); }
#line 4608 "lexer.c"
yy245:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'w': goto yy281;
		default: goto yy45;
	}
yy246:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy247;
	}
yy247:
#line 321 "lexer.re"
	{ return token(TRUE); }
#line 4686 "lexer.c"
yy248:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'o': goto yy283;
		default: goto yy45;
	}
yy249:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy250;
	}
yy250:
#line 315 "lexer.re"
	{ yylval.string = js_strndup(start, scanner.cursor - start); return token(IDENTIFIER); }
#line 4764 "lexer.c"
yy251:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy284;
		default: goto yy45;
	}
yy252:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy253;
	}
yy253:
#line 317 "lexer.re"
	{ return token(WITH); }
#line 4842 "lexer.c"
yy254:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'd': goto yy286;
		default: goto yy45;
	}
yy255:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy256;
	}
yy256:
#line 319 "lexer.re"
	{ yylval.string = js_strndup(start, scanner.cursor - start); return token(IDENTIFIER); }
#line 4920 "lexer.c"
yy257:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy258;
	}
yy258:
#line 285 "lexer.re"
	{ return token(BREAK); }
#line 4992 "lexer.c"
yy259:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy260;
	}
yy260:
#line 287 "lexer.re"
	{ return token(CATCH); }
#line 5064 "lexer.c"
yy261:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy262;
	}
yy262:
#line 288 "lexer.re"
	{ return token(CLASS); }
#line 5136 "lexer.c"
yy263:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy264;
	}
yy264:
#line 289 "lexer.re"
	{ return token(CONST); }
#line 5208 "lexer.c"
yy265:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'n': goto yy288;
		default: goto yy45;
	}
yy266:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'g': goto yy289;
		default: goto yy45;
	}
yy267:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'l': goto yy290;
		default: goto yy45;
	}
yy268:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy291;
		default: goto yy45;
	}
yy269:
	yych = *++scanner.cursor;
	switch (yych) {
		case 't': goto yy293;
		default: goto yy45;
	}
yy270:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'd': goto yy295;
		default: goto yy45;
	}
yy271:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy272;
	}
yy272:
#line 322 "lexer.re"
	{ return token(FALSE); }
#line 5316 "lexer.c"
yy273:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'l': goto yy296;
		default: goto yy45;
	}
yy274:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'i': goto yy297;
		default: goto yy45;
	}
yy275:
	yych = *++scanner.cursor;
	switch (yych) {
		case 't': goto yy298;
		default: goto yy45;
	}
yy276:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'n': goto yy300;
		default: goto yy45;
	}
yy277:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'n': goto yy301;
		default: goto yy45;
	}
yy278:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy279;
	}
yy279:
#line 308 "lexer.re"
	{ return token(SUPER); }
#line 5418 "lexer.c"
yy280:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'h': goto yy303;
		default: goto yy45;
	}
yy281:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy282;
	}
yy282:
#line 311 "lexer.re"
	{ return token(THROW); }
#line 5496 "lexer.c"
yy283:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'f': goto yy305;
		default: goto yy45;
	}
yy284:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy285;
	}
yy285:
#line 316 "lexer.re"
	{ return token(WHILE); }
#line 5574 "lexer.c"
yy286:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy287;
	}
yy287:
#line 318 "lexer.re"
	{ return token(YIELD); }
#line 5646 "lexer.c"
yy288:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'u': goto yy307;
		default: goto yy45;
	}
yy289:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy308;
		default: goto yy45;
	}
yy290:
	yych = *++scanner.cursor;
	switch (yych) {
		case 't': goto yy309;
		default: goto yy45;
	}
yy291:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy292;
	}
yy292:
#line 293 "lexer.re"
	{ return token(DELETE); }
#line 5736 "lexer.c"
yy293:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy294;
	}
yy294:
#line 296 "lexer.re"
	{ return token(EXPORT); }
#line 5808 "lexer.c"
yy295:
	yych = *++scanner.cursor;
	switch (yych) {
		case 's': goto yy311;
		default: goto yy45;
	}
yy296:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'y': goto yy313;
		default: goto yy45;
	}
yy297:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'o': goto yy315;
		default: goto yy45;
	}
yy298:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy299;
	}
yy299:
#line 302 "lexer.re"
	{ return token(IMPORT); }
#line 5898 "lexer.c"
yy300:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'c': goto yy316;
		default: goto yy45;
	}
yy301:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy302;
	}
yy302:
#line 307 "lexer.re"
	{ return token(RETURN); }
#line 5976 "lexer.c"
yy303:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy304;
	}
yy304:
#line 309 "lexer.re"
	{ return token(SWITCH); }
#line 6048 "lexer.c"
yy305:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy306;
	}
yy306:
#line 313 "lexer.re"
	{ return token(TYPEOF); }
#line 6120 "lexer.c"
yy307:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy317;
		default: goto yy45;
	}
yy308:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'r': goto yy319;
		default: goto yy45;
	}
yy309:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy310;
	}
yy310:
#line 292 "lexer.re"
	{ return token(DEFAULT); }
#line 6204 "lexer.c"
yy311:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy312;
	}
yy312:
#line 297 "lexer.re"
	{ return token(EXTENDS); }
#line 6276 "lexer.c"
yy313:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy314;
	}
yy314:
#line 298 "lexer.re"
	{ return token(FINALLY); }
#line 6348 "lexer.c"
yy315:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'n': goto yy321;
		default: goto yy45;
	}
yy316:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'e': goto yy323;
		default: goto yy45;
	}
yy317:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy318;
	}
yy318:
#line 290 "lexer.re"
	{ return token(CONTINUE); }
#line 6432 "lexer.c"
yy319:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy320;
	}
yy320:
#line 291 "lexer.re"
	{ return token(DEBUGGER); }
#line 6504 "lexer.c"
yy321:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy322;
	}
yy322:
#line 300 "lexer.re"
	{ return token(FUNCTION); }
#line 6576 "lexer.c"
yy323:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'o': goto yy324;
		default: goto yy45;
	}
yy324:
	yych = *++scanner.cursor;
	switch (yych) {
		case 'f': goto yy325;
		default: goto yy45;
	}
yy325:
	yych = *++scanner.cursor;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy44;
		default: goto yy326;
	}
yy326:
#line 304 "lexer.re"
	{ return token(INSTANCEOF); }
#line 6660 "lexer.c"
}
#line 393 "lexer.re"

}

// parser/AST 构建器用它读取最近一个 token 的位置。
void get_token_position(int *line, int *column) {
    *line = scanner.last_token_line;
    *column = scanner.last_token_column;
}

// 使用当前 lexer_input 重新开始扫描。
void reset_lexer(void) {
    init_scanner((const char *)lexer_input);
}

